### ISSUE TITLE
Auto-completion based on dependencies

### ISSUE THREAD

**Issue by MikaelSmith** [jpogran/puppet-vscode#1]
Auto-completion based on only the modules in your metadata.json dependencies, or based on a specified modulepath. I'd like to only get auto-completion for things that will be available when compiling the catalog.

**Comment by glennsarti** [comment]
The current language server uses the puppet-agent installation and settings to determine auto-complete etc. Would this be enough?  It won't autocomplete for modules that are under development, only ones that are installed into the puppet-agent modulepath as set by the current settings.

**Comment by MikaelSmith** [comment]
That seems ok for now. Might be nice to eventually add the ability to modify the modulepath for auto-complete.

**Comment by glennsarti** [comment]
Yeah...that gets a bit tricky.  I'd need to get Puppet to reload the module path everytime the user makes a change to the file which takes a long time.

**Comment by jpogran** [comment]
Closing as implemented for now, with what is loaded on start. The time penalty for autocomplete makes this not something we can implement now with the current state of things. We may eventually add a command that the user can specifically request a reload.
