### ISSUE TITLE
Fix insert on class code

### ISSUE THREAD

**Issue by tspeigner** [jpogran/puppet-vscode#118]
The problem is that when a new class is created and then I start entering the code it adds 4 spaces to where the code starts, where it should only start with 2.

**Comment by jpogran** [comment]
Are you sure that's not the indent setting in VSCode? The default indent is 4 spaces IIRC.

**Comment by glennsarti** [comment]
Also the newer version of VSCode now has "smart" indenting so it adapts the indenting on paste/insert operations.  https://code.visualstudio.com/updates/v1_14#_auto-indent-on-type-move-lines-and-paste

**Comment by tspeigner** [comment]
yep, you are right @jpogran.  thanks for the heads up on that.  still finding my away around VS Code

**Comment by glennsarti** [comment]
I'll close this off for now.
