### ISSUE TITLE
Puppet Agent not found from custom install location

### ISSUE THREAD

**Issue by tmannerm** [jpogran/puppet-vscode#120]
I have Puppet Agent installed on custom directory and this extension seems to fail with a "Could not find Puppet Agent installed at "C:\Program Files\Puppet Labs\Puppet". Functionality will be limited to syntax highlighting" warning and refuse to work. Can't find a way to set the correct path but it would be optimum if the Puppet Agent installation location would be detected automatically.

**Comment by jpogran** [comment]
The reason is because that path is hardcoded. You're right, it should be configurable or discoverable.

**Comment by glennsarti** [comment]
Can probably make this a configuration parameter.  Might be hard to discover due to the lack of environment variable etc. etc.

**Comment by jpogran** [comment]
@tmannerm I've added a PR for this. We'll try to get this into the 0.7 release
