### ISSUE TITLE
Inline disabled lint checks are not honored

### ISSUE THREAD

**Issue by seanabraham** [jpogran/puppet-vscode#125]
When disabling a lint check via https://github.com/rodjek/puppet-lint#disable-checks-within-puppet-code (for example, on a long line), the lint error is still reported by the extension.

**Comment by glennsarti** [comment]
Thanks Sean.  I'll try and repro this and see what's going on.

**Comment by glennsarti** [comment]
At the very least, I can see where we can increase our testing coverage. Yay for more tests!!

**Comment by glennsarti** [comment]
Fix PR is up at https://github.com/jpogran/puppet-vscode/pull/129

**Comment by glennsarti** [comment]
Closing.  Will be available in the 0.7.0 release of the extension.

**Comment by glennsarti** [comment]
Thanks again @seanabraham for the taking the time to report this!

**Comment by seanabraham** [comment]
My pleasure @glennsarti! Thank you for the quick fix!
