### ISSUE TITLE
Extension says it can't find Puppet Agent if version 3.7.4 is installed

### ISSUE THREAD

**Issue by JohnEricson** [jpogran/puppet-vscode#163]
Puppet extension version: 0.7.1
Puppet agent version: 3.7.4
OS: Windows 10 x64
Visual Code: 1.16.1

When I start Visual Code I get the warning "Could not find a valid Puppet Agent installation. Functionality will be limited to syntax highlighting" when I have Puppet Agent 3.7.4 installed.
Upgrading to Puppet Agent version 4.10.8 solves it but I would like to be able to run the older version.

**Comment by jpogran** [comment]
Thanks for the report @JohnEricson.  IIRC Puppet changed paths to the binaries around the 3.X timeline, so that might explain why the extension can't find your agent install. Unfortunately Puppet 3.7.X has been [EOL](https://puppet.com/misc/puppet-enterprise-lifecycle) for awhile now, so even if we added sufficient detection logic to account for the 3.7.X differences we might have more issues using such an old agent.

**Comment by clxnetom** [comment]
Getting the exact same warning with 5.3.2.

Puppet extension version: 0.7.1
Puppet agent version: 5.3.2 (installed using gem)
OS: Ubuntu 17.04
Visual Code: 1.17.0

```bash
$ which puppet
/usr/local/bin/puppet
```

**Comment by JohnEricson** [comment]
That is correct @jpogran. I can see that Puppet Agent 4.10.8 installs under _C:\Program Files\Puppet Labs\Puppet_ while 3.7.4 installs under _C:\Program Files\Puppet Labs\Puppet Enterprise_.

I've tried to change this in Visual Code's User Settings in the puppet.puppetAgentDir setting but that doesn't help. Neither does installing the old agent in _C:\Program Files\Puppet Labs\Puppet_.

I guess I have another good reason to look into upgrading :-)

**Comment by jpogran** [comment]
@clxnetom Thanks for the additional info. Your issue comes not from the version, but from the way puppet was packaged on that platform. See #164 for more information.

In short, we're working on a fix

**Comment by jpogran** [comment]
@JohnEricson I know this isn't trivial sometimes, but I'd recommend upgrading, there is alot of performance improvements, nevermind tons of features you'll get by moving to current versions.

**Comment by jpogran** [comment]
Closing as this is related to an EOL version of Puppet, and not the extension
