### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by phothet** [jpogran/puppet-vscode#165]
When I clicked the link `How to run the Language Server for Develoment` on the page https://github.com/jpogran/puppet-vscode#run-the-language-server, I got 404 error. And Develoment is missing **p**.

Thank you.

**Comment by phothet** [comment]
Perhaps this is the correct link?

https://github.com/jpogran/puppet-vscode/blob/master/server/README.md#how-to-run-the-client-and-server-for-development

**Comment by glennsarti** [comment]
Hi @phothet.  Whoops, looks we didn't type something correctly there.  Nice find and we'll get the fixed soon.

**Comment by glennsarti** [comment]
Fixed.
