### ISSUE TITLE
Using f12 / ctrl f12

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [jpogran/puppet-vscode#166]
Neither f12 nor ctrl f12 appear to work in visual studio code with the 0.7.1 version of the extension installed.
I cannot select a class (eg: users::my_name ) and press a key to go to the implementation/definition of that class. Should this work? maybe i am using the wrong shortcut?

**Comment by glennsarti** [comment]
Hi @jgrammen-agilitypr .  The extension has never supported the peek definition feature.  What I will do is add that as a feature request.

**Comment by jgrammen-agilitypr** [comment]
Hello, Thank you for the reply.
Ok, yes making it a feature request sounds about right.
It certainly would be very useful.
I currently use Geppetto and being able to jump to declaration / definition is something I use frequently.

**Comment by glennsarti** [comment]
Ahh ok.  This may require some fiddling within Puppet to get that information but in theory it sounds like it's possible.

**Comment by jgrammen-agilitypr** [comment]
In case my feature request was not completely clear, hear are a few images:
![gotodeclaration](https://user-images.githubusercontent.com/22965146/31560648-20507e5e-b023-11e7-90fc-1afb484d44c7.png)
![gotodeclarationf2](https://user-images.githubusercontent.com/22965146/31560649-2060b922-b023-11e7-944a-ff82aad4824f.png)
When you click on the button it opens the file that defines Class mm::motd

**Comment by glennsarti** [comment]
Yup that's what I'm thinking of:

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#goto-definition-request

**Comment by mdwheele** [comment]
@glennsarti, do you think this is something achievable without a ton of experience / intimate knowledge of VS Code extensions? I would be willing to make an attempt if you could point me in the right direction to get started.

**Comment by glennsarti** [comment]
Responding to requests from VScode and crafting the write JSON messages (as per language server protocol is easy enough).

The thing I don't know is;

Does puppet keep a track of which puppet classes were loaded from which file?
Does puppet keep track of which puppet functions were loaded from which file?
If that's stored somewhere then wiring that up isn't too hard.
If that's _not_ stored that will require monkey patching the loaders in Puppet, and THAT is not a simple thing to do.

**Comment by jgrammen-agilitypr** [comment]
any chance on this getting merged in? or is it still a work in progress?

**Comment by glennsarti** [comment]
This is still work in progress.  I've been unable to work on it for a while due to family issues.

Current state is it mostly works.  Still adding and fixing tests

**Comment by glennsarti** [comment]
@jgrammen-agilitypr I have a beta build you can try out if you wish

You can download the VSIX from https://ci.appveyor.com/project/jpogran/puppet-vscode/build/0.7.0-appv.373/job/7aq7d1miv6gw46sn/artifacts

**Comment by jgrammen-agilitypr** [comment]
Thank you for the update. I try and checkout that beta build.

**Comment by jgrammen-agilitypr** [comment]
So I tried out that beta build, and I must have something incorrectly configured.
pressing f12 on any class name just sends me to
`C:\Program Files\Puppet Labs\Puppet\sys\ruby\lib\ruby\vendor_ruby\puppet\parser\functions\include.rb`
or, I get a popup with 'no definition found' (in this case it appears not to be following the full class name, as in ignoring everything before the :: )

**Comment by glennsarti** [comment]
Hrmm ok well the good news is it's not the definition provider's fault.  Looks like I have a bug in the cursor detection bit.  I can repro that issue and I'll get it fixed.

**Comment by glennsarti** [comment]
@jgrammen-agilitypr Updated the code.  It now detects the name correctly.  Added some tests for this too.  Extension is at https://ci.appveyor.com/project/jpogran/puppet-vscode/build/0.7.0-appv.375/job/dbcqc5mfmkcjgvk9/artifacts

Still need to test for fully qualified names yet...

**Comment by glennsarti** [comment]
@jgrammen-agilitypr ... and updated for root class names `::<class>`

Test extenstion at.
https://ci.appveyor.com/project/jpogran/puppet-vscode/build/0.7.0-appv.378/job/g3c3jp9rrjcrgcq3/artifacts

**Comment by jgrammen-agilitypr** [comment]
Thank you for your continued work.
I have tested 0.7.0-appv.378 and I still get "No definition found for 'xxx' "

I am attaching a screenshot to see if that helps you understand why it doesn't work for me.
I strongly suspect that i have something setup incorrectly in my environment.

![nodefinition](https://user-images.githubusercontent.com/22965146/34108555-83cfacbe-e3ce-11e7-8f25-8785b94e0783.png)

**Comment by glennsarti** [comment]
@jgrammen-agilitypr  That is awesome...  and thank you for helping me test it!!

I'll repro that tomorrow.

**Comment by jgrammen-agilitypr** [comment]
I am happy to be of assistance, especially since this feature is of particular interest to me (this feature will be very useful to me).

**Comment by glennsarti** [comment]
@jgrammen-agilitypr Updated for class titles

https://github.com/jpogran/puppet-vscode/pull/193/commits/8eacfc5ce62a49a9ee3fb2b3bc58da0fcc1084e7

Extension is at https://ci.appveyor.com/project/jpogran/puppet-vscode/build/0.7.0-appv.379/job/ru9ql6el47yq2fpv/artifacts

**Comment by jgrammen-agilitypr** [comment]
I am sad to report that build 379, is still giving me the same error.
I am again providing a screen shot.

I also noticed that the f12 is still only picking up part of the class name. In the picture attached you can see the popup says "No definition found for 'nodejs' ", instead of "No definition found for 'mm::nodejs' "

I restarted visual studio code, after installing the plugin.
I made sure puppet (5.3.2) was running as you can see in the screenshot.
I am on windows 10 64 bit.

![nodefinition379](https://user-images.githubusercontent.com/22965146/34159489-75a5287a-e497-11e7-8248-a21e883f0818.png)

**Comment by glennsarti** [comment]
@jgrammen-agilitypr Hi again.  So it appears the message VSCode shows you in the editor is it trying to be "helpful" but failing.

The language server cannot return the _actual_ string its using to find the definition (not part of the protocol) so VSCode does its best and it knows that double colons `::` are a selection delimiter so it just chooses the text between them.  Thus you're seeing it say 'nodejs' but the _actual_ string that is used is 'mm::nodejs'.

I added some extra debugging and recorded what VSCode sees as opposed to the language server and you see the difference.

![puppet-finddefn](https://user-images.githubusercontent.com/5819622/34186812-ec59771a-e568-11e7-8ec9-2cca0edca0bd.gif)

Also note that as I move the cursor VSCode is highlighting the text even without me trying to find the definition.

The double colon "stuff" is defined in the Puppet language syntax file so I don't think we can change that easily.
---
But that doesn't solve the second problem.  Why didn't it find the definition?

I will be guessing a bit here, but I think you may be hitting one of the restrictions of the current language server implementation.  At the moment I can only detect functions, classes, types etc. that exist in the default places, for the default environment, in the puppet agent - NOT the the workspace of the VSCode editor.

I suspect the `mm::nodejs` class/type is not installed in that location e.g. if you do a `puppet module list` it won't find a module called mm.

Does this sound like what you have setup?
---
Note this is something I desperately want to change but custom puppet types and providers make this very difficult.

**Comment by jgrammen-agilitypr** [comment]
I apologize for not understanding how the blue pop up works. I was under the impression that what it displayed was what it was searching for.

You are correct about it looking in the puppet agent's default environment and codedir, not my workspaces.
After editing my users's puppet.conf file (~/.puppetlabs/etc/puppet/puppet.conf)
and adding : codedir=C:\Users\[username]\Documents\[code directory]\puppet
it now works correctly and is awesome :).

**Comment by glennsarti** [comment]
@jgrammen-agilitypr I had no idea about blue pop until you mentioned it.  I tried a few things to make it change but to no avail.  I'll probably log a ticket against VS Code for that.

Sounds like you'd be happy for this feature to ship right now.  I'll also log an issue to get it to understand and parse workspaces for classes and types.

**Comment by jgrammen-agilitypr** [comment]
I was on holidays and did not see this until today, yes after correcting the puppet agents environment and codedir (via users's puppet.conf file), the feature works as I would expect, and appears to be ready to ship.

and I agree with the next improvement (via a new ticket) being having it understand and parse workspaces.

**Comment by glennsarti** [comment]
This feature was merged and will be available next release.  Closing this issue as resolved.
