### ISSUE TITLE
Colourisation bug: apostrophe's in parameter comment blocks

### ISSUE THREAD

**Issue by petems** [jpogran/puppet-vscode#169]
When an apostrophe is used in a comment block in the parameters, highlighting is broken for the whole file

<img width="539" alt="screenshot 2017-10-15 22 42 43" src="https://user-images.githubusercontent.com/1064715/31589495-54841e64-b1fa-11e7-8fcd-6676195c0ae3.png">

**Comment by glennsarti** [comment]
Looks like it's related to the parenthesis coding `( )`

e.g. this works ok
``` puppet
class dhcp (
  Optional[Arrau[String]] $dndomain = undef,
  Array[something] $nameservs = [ '8.8.8.8', '8.8.4.4' ],
  ) {
  # this is some text that can't colorize
  } 
}
```

e.g. this does not work ok
``` puppet
class dhcp (
  Optional[Arrau[String]] $dndomain = undef,
  Array[something] $nameservs = [ '8.8.8.8', '8.8.4.4' ],
  # this is some text that can't colorize
  ) {
  # this is some text that can't colorize
  } 
}
```

**Comment by glennsarti** [comment]
Interesting the github colorisation fails too.

**Comment by petems** [comment]
Yeah, I recently found out that GIthub's linguist uses https://github.com/russCloak/SublimePuppet, which probably has the same bug

**Comment by glennsarti** [comment]
Fix PR at #170

**Comment by glennsarti** [comment]
I have a suspicion I'll need to do an upstream PR to SublimePuppet seem as though we share the same file.

**Comment by glennsarti** [comment]
@petems You can try with this build of the extension - https://ci.appveyor.com/project/jpogran/puppet-vscode/build/0.7.0-appv.296/job/sox6hii1yeviqd3l/artifacts

**Comment by glennsarti** [comment]
Closing as fixed in merge
