### ISSUE TITLE
Could not find a valid Puppet Agent installation. Functionality will be limited to syntax highlighting

### ISSUE THREAD

**Issue by mmerfort** [jpogran/puppet-vscode#175]
I'm using a clean installation of Visual Studio Code 1.17.2-1 with version 0.7.1 of this as the only plugin on Arch Linux with Puppet 5.1.0.

I'm getting this message when I open a .pp file.

**Comment by jpogran** [comment]
Thanks for the report @mmerfort, can you paste what path Puppet agent is installed to?

**Comment by mmerfort** [comment]
It's installed to /usr/bin/puppet.

I think Arch Linux does it's own thing by not installing things in /opt/puppetlabs.

**Comment by jpogran** [comment]
Yep, that's the reason. I think you can get around this by setting the path manually, until we figure out a better discovery mechanism for the path or switch to using the PDK instead.

You can set the path by adding `puppet.puppetAgentDir` to your VS Code settings and entering in your agent directory there. It should autocomplete for you inside the editor.

**Comment by mmerfort** [comment]
I tried setting this to /usr/lib/ruby/vendor_ruby/2.4.0/puppet but this didn't work.
I also tried cloning the puppet code from https://github.com/puppetlabs/puppet to /opt/puppetlabs/puppet and setting that but this didn't work either.

**Comment by jpogran** [comment]
I meant the path to the Puppet agent install, not to the ruby directory

```
"puppet.puppetAgentDir":"/usr/bin/puppet"
```

If it were installed to /opt/puppetlabs it would be:

```
"puppet.puppetAgentDir":"/opt/puppetlabs/puppet"
```

If that doesn't work, then we'll have to adjust our path use

**Comment by mmerfort** [comment]
No, this doesn't work either.

**Comment by jpogran** [comment]
I'm sorry that didn't work. Good news though is that we took this under advisement and decided in #177 to remove the VERSION file check entirely. This is currently committed to master, and should be released within the next week
