### ISSUE TITLE
Node Graph Doesn't Seem to Accept *nix Paths on a Windows Machine

### ISSUE THREAD

**Issue by michaeltlombardi** [jpogran/puppet-vscode#181]
### What Versions are you running?

+ **OS Version:** Windows 10
+ **VSCode Version:** 1.17.2
+ **Puppet Extension Version:**master (6886aaf)
+ **Puppet Agent Version:** 5.3.2 (`puppet --version`)
+ **PDK Version (if applicable):** Not installed.

### What You Are Seeing?
When I try to create a manifest that includes linux-y paths using the extension on a Windows machine, the node graph presents a parsing error. It does not do this for Windows-friendly fully qualified paths (`C:\...`), but does for paths like `/usr/bin/...`

![image](https://user-images.githubusercontent.com/14190564/32083067-97839f30-ba85-11e7-8bc5-17cd32602671.png)

![image](https://user-images.githubusercontent.com/14190564/32083084-bf920e58-ba85-11e7-95b3-3fcae4fdca31.png)

### What is Expected?
The node graph should correctly parse file paths for manifests that may not apply to my workstation.

### How Did You Get This To Happen? (Steps to Reproduce)
Clone and build from master, create `example.pp`, and open node graph from command palette.

```
exec { 'apt-update': 
  command => '/usr/bin/apt-get update',
}
file {'/home/me/derp':
  ensure => present,
}
```

### Output Log

None.

**Comment by glennsarti** [comment]
This is a manifestation of the same issue in https://github.com/jpogran/puppet-vscode/issues/171

**Comment by glennsarti** [comment]
Closing as a duplicate issue of #171
