### ISSUE TITLE
task input_method 'powershell' fails validation

### ISSUE THREAD

**Issue by jessereynolds** [jpogran/puppet-vscode#201]
I suspect this is due to the json schema for task metadata on the Forge disallowing 'powershell' input_method so probably an issue upstream to this issue. 

Refer:
- https://tickets.puppetlabs.com/browse/FORGE-404
- https://github.com/puppetlabs/pdk/issues/369

**Comment by glennsarti** [comment]
Thanks @jessereynolds .  You are correct, the VS Code extension consumes a JSON document hosted on the forge.  Your PR for FORGE-404 will fix this.

**Comment by glennsarti** [comment]
Closing as this issue cannot be resolved by the VS Code plugin.
