### ISSUE TITLE
Debugger breakpoints dont work

### ISSUE THREAD

**Issue by dotanspector** [jpogran/puppet-vscode#206]
### What Versions are you running?

OS Version: Mac OSX Sierra
VSCode Version: 1.18.1
Puppet Extension Version: 0.8.0
Puppet Agent Version: 5.0.0
PDK Version (if applicable):1.2.1

### What You Are Seeing?
    puppet applying catalog even when using breakpoints:
    "puppet exited with 0"

### What is Expected?
Be able to debug (use step-out/into/continue etc..)

 
### How Did You Get This To Happen? (Steps to Reproduce)
        {
            "type": "Puppet",
            "request": "launch",
            "name": "Puppet Apply current file",
            "manifest": "${file}",
            "args": [],
            "noop": true,
            "cwd": "${file}"
        }
### Output Log
```
* The Puppet debugger is an experimental feature *
* Debug Server v0.0.1                            *
**************************************************

puppet apply /Users/dotan.spector/IntelliJ_workspaces/<path>streamer/manifests/test.pp --detailed-exitcodes --logdest debugserver --noop
Warning: Facter: effective gid 1371015622 does not have a group entry.
Notice: Compiled catalog for <hostname> in environment production in 0.54 seconds
Notice: Applied catalog in 0.02 seconds
puppet exited with 0
```

**Comment by glennsarti** [comment]
Is the manifest you're using 
``` puppet
class test {
  $dgfs = 12
  user { 'blah':
    ensure => present
  }
  notify { 'bla': }

}
``` 
?

**Comment by dotanspector** [comment]
yes

**Comment by glennsarti** [comment]
Ahh ok.

You defined the class but never included it.  Try;

``` puppet
class test {
  $dgfs = 12
  user { 'blah':
    ensure => present
  }
  notify { 'bla': }

}

include test
```

**Comment by dotanspector** [comment]
working . thanks!!
