### ISSUE TITLE
Issues with hover over not working and requiring a manual restart of the current session via command palette

### ISSUE THREAD

**Issue by jdub55** [jpogran/puppet-vscode#209]
### What Versions are you running?

OS Version: Mac OS (Sierra)
VSCode Version: 1.19
Puppet Extension Version: 0.80
Puppet Agent Version: 5.3.3
PDK Version (if applicable):

### What You Are Seeing?
Frequently the hover over text for things like "class", etc. does not work and requires a manual restart of the current session via the command palette. 

### What is Expected?

Hover over should work consistently and a manual restart of the session should not be required. 

### How Did You Get This To Happen? (Steps to Reproduce)

Work in a .pp file or file(s) in VSCode long enough and this will occur. I haven't been able to isolate is down to a timing issue yet but I think it's possible this is occurring after the PC gets awoken from sleep mode?

**Comment by glennsarti** [comment]
Closing issue as it appears to have gone stale.  Feel free to reopen if you would like to pursue this.
