### ISSUE TITLE
Language server fails to start

### ISSUE THREAD

**Issue by mrysbekov** [jpogran/puppet-vscode#211]
### What Versions are you running?

OS Version: Windows 10 Pro (x64)
VSCode Version: 1.19.3
Puppet Extension Version: 0.8.0
Puppet Agent Version: ?
PDK Version (if applicable): ?

### What You Are Seeing?

When I open a .pp file I see a yellow "Starting Puppet..." text in VSC status bar that never changes to anything. Pupet syntax highlighting works but no warnings/errors related to Puppet code are reported. Uninstalling Puppet extension and installing it again does not solve the issue.

### What is Expected?

The yellow "Starting Puppet..." text in the status bar should change to "Loading Puppet (x %)" and then to Puppet version in green. Puppet code warnings/errors should be reported in Problems section.

### How Did You Get This To Happen? (Steps to Reproduce)

I can't recall any particular actions that triggered this.

### Output Log

I've set the value of "puppet.languageserver.debugFilePath" paratmeter to "D:\\puppet.log", but this file is not created when I start VSC, open a .pp file and observe the issue.

**Comment by glennsarti** [comment]
Hi @mrysbekov.  What version of the Puppet Agent do you have installed?.  You can normally get that using `puppet --version`

Also, is there file called `%TEMP%\puppet_language_server_crash.txt` ?

**Comment by mrysbekov** [comment]
Hi Glenn,

I tried executing "puppet --version" but the command failed. I started investigating and found that my whole Ruby installation was corrupted. I ended up reinstalling Ruby 2.4.3 and installing Puppet gem again. I'm happy to say that Puppet extension now works as expected, and there's a nice green "5.3.3" text in the status bar of VSC.

Thanks!

**Comment by glennsarti** [comment]
@mrysbekov Excellent!
