### ISSUE TITLE
Error when validating epp files

### ISSUE THREAD

**Issue by rogermartensson** [jpogran/puppet-vscode#218]
### What Versions are you running?

OS Version: Windows 10
VSCode Version: 1.20.1
Puppet Extension Version: 0.9.0
Puppet Agent Version: 5.4
PDK Version (if applicable): 1.3

### What You Are Seeing?
Getting a validating an epp file.

### What is Expected?
No validation error at all.

### How Did You Get This To Happen? (Steps to Reproduce)
Created a simple epp with input header.

Example file. template.txt.epp:
<%- String $tmp
| -%>

<%= $tmp %>
### Output Log
Could not parse for environment *root*: Syntax error at '<' (line: 1, column: 1)

My guess is that "puppet parser validate" is used and that will emit this error. 
The correct command should be "puppet epp validate"

**Comment by glennsarti** [comment]
@rogermartensson Yup, in essence that's what's happening.  I haven't adding any testing for that yet either.  I have some other code that could be useful, so I don't _think_ it'll be too hard to do.  At least get some simple validation going, and not throw stupid errors.

Thanks for the error report!

**Comment by glennsarti** [comment]
I'll try and get this in for the next release.

**Comment by glennsarti** [comment]
Preview build is at https://ci.appveyor.com/project/jpogran/puppet-vscode/build/0.7.0-appv.421/job/f3qkdkc46ng4ea6m/artifacts
