### ISSUE TITLE
Graph Node says No resources are created for class

### ISSUE THREAD

**Issue by tebeco** [jpogran/puppet-vscode#221]
### What Versions are you running?
OS Version: Win 10
VSCode Version: 1.20.1
Puppet Extension Version: 0.9.0
Puppet Agent Version: 5.4.0
PDK Version (if applicable): 1.3.2

### What You Are Seeing?
The page telling me that i create create no resources from that `.pp` file

### What is Expected?
Would love to see a graph

### How Did You Get This To Happen? (Steps to Reproduce)
* Create a FLAT `.pp` file with the content :
```
$foo_dir = 'D:\foo'
$bar_dir = "${foo_dir}\\bar"
$foobar_file = "D:\\foobar.txt"

file { $foo_dir:
    ensure => directory,
}
file { $bar_dir:
  ensure => directory,
}
file  { $foobar_file:
  ensure => file
}
```
* Then open the `Puppet : Open Node Graph to the side` view ==> Works
* Use the Command palette to `Puppet: PDK New Class`
```
# foo::foobar
#
# A description of what this class does
#
# @summary A short summary of the purpose of this class
#
# @example
#   include foo::foobar
class foo::foobar {
  # Same content as flat file here :
  $foo_dir = 'D:\foo'
  $bar_dir = "${foo_dir}\\bar"
  $foobar_file = "D:\\foobar.txt"

  file { $foo_dir:
    ensure => directory,
  }
  file { $bar_dir:
    ensure => directory,
  }
  file  { $foobar_file:
    ensure => file
  }
}
```
* Then open the `Puppet : Open Node Graph to the side` view ==> Got the page telling me i create no resource

Cannot give the Logs since the extension cannot run Lang Server 90% of the time because of https://github.com/jpogran/puppet-vscode/issues/220

**Comment by glennsarti** [comment]
Is the
```
$foo_dir = 'D:\foo'
$bar_dir = "${foo_dir}\\bar"
$foobar_file = "D:\\foobar.txt"
..
```
inside the class or exactly as you have above?

**Comment by tebeco** [comment]
I do have a typo ^^
everything should be within the class ;)

**Comment by glennsarti** [comment]
Ahh in that case ..

You defined the class but you didn't create it i.e. missing an include statement

`include foo::foobar`

**Comment by tebeco** [comment]
I really just began "trying" to work with puppet so... where should i add this include statement ?

**Comment by glennsarti** [comment]
Down the bottom.

``` puppet
class foo::foobar {
  $foo_dir = 'D:\foo'
  $bar_dir = "${foo_dir}\\bar"
  $foobar_file = "D:\\foobar.txtxx"

  file { $foo_dir:
      ensure => directory,
  }
  file { $bar_dir:
    ensure => directory,
  }
  file  { $foobar_file:
    ensure => file
  }
}

include foo::foobar
```

**Comment by tebeco** [comment]
thx
