### ISSUE TITLE
Think of a name for the new github org

### ISSUE THREAD

**Issue by glennsarti** [jpogran/puppet-vscode#223]
We need a cool memorable name for a github org for this repo.

Add your idea...and vote with thumbs up/down

**Comment by michaeltlombardi** [comment]
shadowpuppet

**Comment by glennsarti** [comment]
the obvious one - puppet-editor

**Comment by glennsarti** [comment]
lingua pupa   (latin: Puppet language)

**Comment by glennsarti** [comment]
nom-de-plume   (French: pen name)

I just like the sound of it :-)

**Comment by jpogran** [comment]
lingua-pupuli has the most upvotes, going with that one

**Comment by glennsarti** [comment]
It is done .... https://github.com/lingua-pupuli

Now to figure out a logo for it .... :-)
