### ISSUE TITLE
Puppetfile errors

### ISSUE THREAD

**Issue by HerveMARTIN** [jpogran/puppet-vscode#235]
### What Versions are you running?

OS Version: Ubuntu
VSCode Version: 1.21.0
Puppet Extension Version: 0.9.0
Puppet Agent Version: 4.8.2
PDK Version (if applicable):

### What You Are Seeing?
When editing my Puppetfile, this puppet module shows an error after the period of the first mod, and if i disable this extension, the error disappear...
```mod 'puppetlabs-ntp', '7.0.0'```
The error message is : 

> [Puppet] attempt to pass argument list to the function 'mod' which cannot be called without parentheses at line 4:21 

### What is Expected?
2 solutions : don't parse Puppetfile or parse it with "r10k puppetfile check"

### Output Log
[Puppet] attempt to pass argument list to the function 'mod' which cannot be called without parentheses at line 4:21

**Comment by glennsarti** [comment]
Hi @HerveMARTIN .  Thanks for the bug report.  There seems to be two things happening here.

Firstly, this extension doesn't offer support for `Puppetfile`.  You can see in the package.json (https://github.com/jpogran/puppet-vscode/blob/master/client/package.json#L56-L70) that it's only files with `.pp` and `.epp` extensions.  That said it is possibly that VSCode is magically assigning Puppetfile to the Puppet language.  You can reconfigure this by clicking on the language indicator (https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) or modifying your User Settings

``` json
    "files.associations": {
        "Puppetfile": "ruby"
    }
```

Secondly, we are in the process of adding R10K/Control Repo support but that's a while away.  We added a fix for 0.10.0 (https://github.com/jpogran/puppet-vscode/pull/219) which would at least just ignore unknown file types.

**Comment by glennsarti** [comment]
Closing the issue.  Feel free to re-open it you would like to continue this.

**Comment by HerveMARTIN** [comment]
Ok, files.associations doesn't solve the problem but I'll wait for the 0.10.0 release.
When will it be available?
