### ISSUE TITLE
Create a way to fix linting errors

### ISSUE THREAD

**Issue by glennsarti** [jpogran/puppet-vscode#50]
Puppet-lint has the ability to fix errors, but the extension doesn't expose that.  Should add this feature.

**Comment by glennsarti** [comment]
Considered just adding a command (puppet lint fix) that just fixes everything....

or perhaps use the codeAction feature to fix a single lint error

**Comment by jpogran** [comment]
`puppet lint fix` is already implemented, but there are problems with it. The command takes the current file, fixes everything, and then replaces the file. VSCode keeps files in memory, so thinks the file has been changed out from under it and asks to save what it thinks is 'current'. We need to implement a refresh of the window after the command is run to fix this.

**Comment by jdub55** [comment]
I gave a short demo at a Puppet Users Group on the VS code extension and this topic came up. It would be really nice to set this as a configurable flag (per workspace?) as to whether or not you want VSCode to automatically fix all your linting errors for you or just warn and display in the "Problems" tab.

**Comment by glennsarti** [comment]
Fixed in #210.  Will be available in next release
