### ISSUE TITLE
Cache Resources, Parameters, and Properties for Completion

### ISSUE THREAD

**Issue by austb** [jpogran/puppet-vscode#62]
As per the comment, the Completion Provider should cache resources, parameters, and properties for quick searching. This will probably be necessary if we want to be able to complete based off the metadata.json (Issue #1  and #52), and maybe even just for larger files.

**Comment by glennsarti** [comment]
Some of this is already done.  In the puppet_helper the types are pre-loaded into a hashtable  (`@types_hash`).  It has some basic multithread detection around it.  It does increase memory usage having them all loaded, but no worse than thrashing disk IO and creating/destroying instances on the fly.

**Comment by glennsarti** [comment]
Confirmed.  This is already cached.  Closing the issue.
