### ISSUE TITLE
Puppet Language Server Windows support

### ISSUE THREAD

**Issue by jpogran** [jpogran/puppet-vscode#65]
As of PR #7, the language server starts with the extension automatically on all supported OS, with the exception of windows. We had trouble starting the language server and keep it running while the extension is loaded using node and child_process.

We should support windows the same as the other platforms.

**Comment by glennsarti** [comment]
@jpogran You happy to close this off?

**Comment by jpogran** [comment]
@glennsarti will test on a fresh VM to avoid the 'works on my machine' problem we both have, then we will close this

**Comment by jpogran** [comment]
After further review, this can be closed as it's tested

**Comment by glennsarti** [comment]
@jpogran Verified it works as expected on Server 2012R2 64bit and Windows 10 32bit.  Required PR #85 first though to create an installable extension.
