### ISSUE TITLE
Prepare of 0.4.0 release

### ISSUE THREAD

**Issue by glennsarti** [jpogran/puppet-vscode#82]
- Update readme
- Confirm the readme looks ok in VSCode
~~- Figure out a name for the extension~~ Will be under James' name for the moment
~~-  Merge PR to move to master~~ Done

We will re-address the naming closer to 1.0. Ship it!

**Comment by austb** [comment]
Just so we have a record here, in VSCode, using the packaged extension, the README Puppet logo image and the animated demo do not load.

**Comment by jpogran** [comment]
@austb we need to follow [these instructions](https://code.visualstudio.com/docs/extensions/publish-extension#_marketplace-integration) in our packaging step in order for the gif to work. The crux is that packaging 'fixes' the urls for any links to point to the github repo, but it assumes all files are in the root, not in a sub folder called client
