### ISSUE TITLE
Code Folding and Block Comments don't work

### ISSUE THREAD

**Issue by jpogran** [jpogran/puppet-vscode#9]
Investigate why code folding and block comments don't appear to work

**Comment by jpogran** [comment]
We appear to be following https://docs.puppet.com/puppet/4.10/lang_comments.html

**Comment by glennsarti** [comment]
I'm probably thinking we should only use the hash character due to:
`This (C-style) comment style is less frequently used than shell-style.`

**Comment by glennsarti** [comment]
Fixed in https://github.com/jpogran/puppet-vscode/pull/15
