### ISSUE TITLE
Suggestions for improving the Marketplace page and installation instructions

### ISSUE THREAD

**Issue by jdub55** [jpogran/puppet-vscode#99]
After going through the install process, I'd like to recommend a couple small changes to the documentation as listed on the Marketplace page (link below). 

https://marketplace.visualstudio.com/items?itemName=jpogran.puppet-vscode

1) While it's probably obvious to a more experienced Puppet user, it wasn't obvious to me how to get the syntax highlighting to work. I tried a few different methods and then realized I needed to be saving the file extension as a .pp file. I tried enabling it through Preferences, but the Puppet listed there had some sort of .json syntax and I didn't get the highlighting or syntax display I was expecting. If there are file extension naming conventions that are supported, I think it would be good to list all the extensions (e.g. .pp, etc.) on this page. 

2) Is puppet-lint required as a separate install or is the installation of the latest Puppet agent locally enough? I ended up installing puppet-lint separately but it wasn't clear to me from the page whether this was a pre-requisite or not? If it is required as a separate 

3) Is the heading "Requirements" a fixed thing in the VS Marketplace? I think a better title would be Dependencies or Pre-requisites. I initially skipped over this section as it was just once sentence with links. I think calling this section a bit more prominent and also letting know which features won't be available if the puppet agent isn't installed would be helpful.

4) Under the "Features" heading, the "Syntax highlighting" and "Code snippets" bullet points are hyperlinks but they just take you back to the main page. Can these hyperlinks be pointed to a valid location or just removed as appropriate?

Thanks,

**Comment by jpogran** [comment]
1. We'll add what file extensions light up the Puppet extension to the readme (which the marketplace uses). When you use something for so long, you start forgetting what it's like with fresh eyes.

2. puppet-lint comes as part of the extension, and works so long as the puppet agent is installed.

3. The heading 'Requirements' is part of the recommended set of headings for VSCode extensions, but there are no hard and fast rules governing inclusion or exclusion that I know of. We'll work on calling out the puppet agent requirement better, and listing that pretty much everything but syntax and snippets won't work without it.

4. They're href's to the section headers for those parts later down. Must not work nicely inside the extension, but they work in the readme on GitHub. I'll look into it, and change it if it can't be fixed.

**Comment by glennsarti** [comment]
Thanks for the feedback @jdub55 !

**Comment by jpogran** [comment]
@jdub55 I updated the readme that shows up in the marketplace with corrections you suggested. You can look at it here: [README.md](https://github.com/jpogran/puppet-vscode/blob/master/client/README.md).

**Comment by jpogran** [comment]
I'm going to close this out. We're looking to get these changes in a 0.5.0 release soon. If there are more suggested changes you can reopen this issue.
